-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS restaurant.customers
(
    id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password_hashed character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    role restaurant.customer_role DEFAULT 'regular_customer'::restaurant.customer_role,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT customers_pkey PRIMARY KEY (id),
    CONSTRAINT customers_email_key UNIQUE (email),
    CONSTRAINT customers_username_key UNIQUE (username)
);

COMMENT ON TABLE restaurant.customers
    IS 'Stores customer information and credentials';

CREATE TABLE IF NOT EXISTS restaurant.menu_items
(
    id serial NOT NULL,
    item_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    item_type restaurant.item_type NOT NULL DEFAULT 'food'::restaurant.item_type,
    item_price numeric(10, 2) NOT NULL,
    item_description text COLLATE pg_catalog."default",
    item_image character varying(255) COLLATE pg_catalog."default",
    is_available boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT menu_items_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE restaurant.menu_items
    IS 'Restaurant menu items catalog';

CREATE TABLE IF NOT EXISTS restaurant.order_items
(
    id serial NOT NULL,
    order_id integer NOT NULL,
    menu_item_id integer NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    unit_price numeric(10, 2) NOT NULL,
    subtotal numeric(10, 2) NOT NULL,
    special_instructions text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT order_items_pkey PRIMARY KEY (id),
    CONSTRAINT order_items_order_id_menu_item_id_key UNIQUE (order_id, menu_item_id)
);

COMMENT ON TABLE restaurant.order_items
    IS 'Individual items in each order';

CREATE TABLE IF NOT EXISTS restaurant.orders
(
    id serial NOT NULL,
    customer_id integer NOT NULL,
    table_id integer NOT NULL,
    staff_id integer,
    order_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    status restaurant.order_status DEFAULT 'pending'::restaurant.order_status,
    total_amount numeric(10, 2) NOT NULL DEFAULT 0.00,
    discount_amount numeric(10, 2) DEFAULT 0.00,
    final_amount numeric(10, 2) NOT NULL DEFAULT 0.00,
    payment_method restaurant.payment_method,
    notes text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    payment_requested boolean DEFAULT false,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE restaurant.orders
    IS 'Customer orders';

CREATE TABLE IF NOT EXISTS restaurant.payments
(
    id serial NOT NULL,
    order_id integer NOT NULL,
    payment_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    payment_method restaurant.payment_method NOT NULL,
    amount_paid numeric(10, 2) NOT NULL,
    payment_status restaurant.payment_status DEFAULT 'pending'::restaurant.payment_status,
    transaction_id character varying(100) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payments_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE restaurant.payments
    IS 'Payment transactions';

CREATE TABLE IF NOT EXISTS restaurant.reservations
(
    id serial NOT NULL,
    customer_id integer NOT NULL,
    table_id integer NOT NULL,
    reservation_date timestamp without time zone NOT NULL,
    duration_hours integer DEFAULT 2,
    number_of_guests integer NOT NULL,
    status restaurant.reservation_status DEFAULT 'pending'::restaurant.reservation_status,
    special_requests text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reservations_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE restaurant.reservations
    IS 'Customer table reservations';

CREATE TABLE IF NOT EXISTS restaurant.reviews
(
    id serial NOT NULL,
    customer_id integer NOT NULL,
    order_id integer,
    rating integer NOT NULL,
    comment text COLLATE pg_catalog."default",
    review_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reviews_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE restaurant.reviews
    IS 'Customer reviews and ratings';

CREATE TABLE IF NOT EXISTS restaurant.staff
(
    id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password_hashed character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    role restaurant.staff_role DEFAULT 'waiter'::restaurant.staff_role,
    salary numeric(10, 2),
    hire_date date DEFAULT CURRENT_DATE,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT staff_pkey PRIMARY KEY (id),
    CONSTRAINT staff_email_key UNIQUE (email),
    CONSTRAINT staff_username_key UNIQUE (username)
);

COMMENT ON TABLE restaurant.staff
    IS 'Stores staff member information and roles';

CREATE TABLE IF NOT EXISTS restaurant.staff_schedules
(
    id serial NOT NULL,
    staff_id integer NOT NULL,
    work_day restaurant.work_day NOT NULL,
    work_shift restaurant.work_shift NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT staff_schedules_pkey PRIMARY KEY (id),
    CONSTRAINT staff_schedules_staff_id_work_day_work_shift_key UNIQUE (staff_id, work_day, work_shift)
);

COMMENT ON TABLE restaurant.staff_schedules
    IS 'Manages staff work schedules';

CREATE TABLE IF NOT EXISTS restaurant.tables
(
    id serial NOT NULL,
    table_number character varying(10) COLLATE pg_catalog."default" NOT NULL,
    table_size integer NOT NULL,
    is_occupied boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tables_pkey PRIMARY KEY (id),
    CONSTRAINT tables_table_number_key UNIQUE (table_number)
);

COMMENT ON TABLE restaurant.tables
    IS 'Restaurant table inventory';

CREATE TABLE IF NOT EXISTS restaurant.vip_requests
(
    id serial NOT NULL,
    customer_id integer NOT NULL,
    status restaurant.viprequeststatus NOT NULL,
    reason character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT vip_requests_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS restaurant.order_items
    ADD CONSTRAINT order_items_menu_item_id_fkey FOREIGN KEY (menu_item_id)
    REFERENCES restaurant.menu_items (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS restaurant.order_items
    ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES restaurant.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_order_items_order_id
    ON restaurant.order_items(order_id);


ALTER TABLE IF EXISTS restaurant.orders
    ADD CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES restaurant.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_orders_customer_id
    ON restaurant.orders(customer_id);


ALTER TABLE IF EXISTS restaurant.orders
    ADD CONSTRAINT orders_staff_id_fkey FOREIGN KEY (staff_id)
    REFERENCES restaurant.staff (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS restaurant.orders
    ADD CONSTRAINT orders_table_id_fkey FOREIGN KEY (table_id)
    REFERENCES restaurant.tables (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_orders_table_id
    ON restaurant.orders(table_id);


ALTER TABLE IF EXISTS restaurant.payments
    ADD CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES restaurant.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS restaurant.reservations
    ADD CONSTRAINT reservations_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES restaurant.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_reservations_customer_id
    ON restaurant.reservations(customer_id);


ALTER TABLE IF EXISTS restaurant.reservations
    ADD CONSTRAINT reservations_table_id_fkey FOREIGN KEY (table_id)
    REFERENCES restaurant.tables (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS restaurant.reviews
    ADD CONSTRAINT reviews_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES restaurant.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS restaurant.reviews
    ADD CONSTRAINT reviews_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES restaurant.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS restaurant.staff_schedules
    ADD CONSTRAINT staff_schedules_staff_id_fkey FOREIGN KEY (staff_id)
    REFERENCES restaurant.staff (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_staff_schedules_staff_id
    ON restaurant.staff_schedules(staff_id);


ALTER TABLE IF EXISTS restaurant.vip_requests
    ADD CONSTRAINT vip_requests_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES restaurant.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;